# Generated by Django 5.0 on 2024-01-02 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'card series',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_in_series', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.cardseries')),
                ('tags', models.ManyToManyField(blank=True, to='cards.tag')),
            ],
            options={
                'ordering': ['pk'],
                'unique_together': {('card_series', 'n_in_series')},
            },
        ),
        migrations.CreateModel(
            name='CardPartial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partial_type', models.CharField(choices=[('text', 'Text'), ('code', 'Code')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_partials', to='cards.card')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('card', 'position')},
            },
        ),
    ]
