# Generated by Django 5.0 on 2024-02-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_owner_cardseries_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpartial',
            name='content',
            field=models.JSONField(),
        ),
    ]
