# Generated by Django 4.2.5 on 2023-09-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_cardseries_options_alter_card_card_series_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['pk']},
        ),
    ]
