# Generated by Django 5.0.6 on 2024-05-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_cardpartial_partial_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpartial',
            name='partial_revision_role',
        ),
        migrations.AddField(
            model_name='cardpartial',
            name='is_prompt',
            field=models.BooleanField(default=True),
        ),
    ]
