# Generated by Django 5.0.6 on 2024-05-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_cardpartial_partial_revision_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpartial',
            name='is_prompt',
            field=models.BooleanField(default=False),
        ),
    ]
