# Generated by Django 5.0.6 on 2024-05-15 23:49

from django.db import migrations, models
from cards.models import CardPartial

def default_prompt_initial_content(apps, schema_editor):
    cps = CardPartial.objects.all()
    for cp in cps:
        if cp.content[0]['type'] == 'text':
            cp.prompt_initial_content = [{'type': 'text', 'children': [{'text': ''}]}]
        else:
            cp.prompt_initial_content = [{'type': 'code', 'children': [{'text': ''}]}]
        cp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_cardpartial_is_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpartial',
            name='prompt_initial_content',
            field=models.JSONField(default=list()),
            preserve_default=False,
        ),
        migrations.RunPython(default_prompt_initial_content)
    ]
