# Generated by Django 5.0.6 on 2024-06-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_cardscore_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardpartial',
            unique_together=set(),
        ),
    ]
