# Generated by Django 5.2.3 on 2025-07-13 08:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_alter_cardpartial_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardscore',
            unique_together={('card', 'owner')},
        ),
    ]
