# Generated by Django 5.2.3 on 2025-09-20 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_alter_cardscore_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('card_series', None), _negated=True), fields=('card_series', 'n_in_series'), name='unique_if_card_series_set'),
        ),
    ]
