# Generated by Django 5.2.3 on 2025-09-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_card_unique_if_card_series_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='n_in_series',
            field=models.IntegerField(default=1),
        ),
    ]
