# Generated by Django 5.2.3 on 2025-09-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_alter_card_n_in_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
