# Generated by Django 5.2.3 on 2025-10-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
