# Generated by Django 5.2.3 on 2026-05-10 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_card_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardscore',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cardscore',
            constraint=models.UniqueConstraint(fields=('owner', 'card'), name='unique_card_score_per_user_card'),
        ),
    ]
